version: "3.9"

services:
  terraform:
    build: .
    platform: linux/amd64 #for Macbook M1/2
    env_file: .env
    environment:
      - AWS_SDK_LOAD_CONFIG=1
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_REGION=${AWS_REGION}
    entrypoint: []
    volumes:
      - .:/work
      - ~/.ssh:/root/.ssh
      - ~/.aws:/root/.aws     
    working_dir: /work/${SUBFOLDER}
